name: ShapeGF
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=11.6.0
  - gdown=4.6.4
  - tensorboard=2.11.0
  - ninja=1.10.2
  - matplotlib-base=3.4.3
  - pytorch=1.12.1
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - torchvision=0.13.1
  - tqdm=4.64.1
  - wandb=0.14.0